#! /bin/bash
# since this is a java program, you probably
# need to use java semantics…


THE_CLASSPATH=
PROGRAM_NAME=Exercise1.java Sort.java
# cd src
for i in `ls ../lib/*.jar`
    do
    THE_CLASSPATH=${THE_CLASSPATH}:${i}
done

javac -classpath ".:${THE_CLASSPATH}" $PROGRAM_NAME

if [ $? -eq 0 ]
then
    echo "compile worked!"
fi

# javac Exercise1.java Sort.java
java Exercise1 random 50 bubble test.txt
